export const OIL_CARD_LIST = 'OIL_CARD_LIST';
export const OIL_CARD_RECHARGE = 'OIL_CARD_RECHARGE';
export const OIL_CARD_DETAIL_INFO = 'OIL_CARD_DETAIL_INFO'
export const SET_NULL_OIL_CARD_LIST = 'SET_NULL_OIL_CARD_LIST'
export const LIST_NULL_FALG = 'LIST_NULL_FALG'